/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Brew (https://sketchfab.com/Espressoul)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/day-7-fan-inktober-2021-51af62a225e841179dc36fbbc3c5ff11
title: Day 7 Fan - INKTOBER 2021
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Fan({ ...props }) {
	const group = useRef();
	const { nodes, materials } = useGLTF('/models/fan.glb');
	useFrame(() => {
		group.current.rotation.y += 0.005;
	});
	return (
		<group ref={group} {...props} dispose={null}>
			<group rotation={[0.1, 0, 0]} position={(0, 0, -0.2)}>
				<group rotation={[0, 0, 0]} scale={0.01} position={[0, -2.3, 0]}>
					{/* MUG */}
					<group position={[0, 182.04, -7.76]}>
						<mesh
							geometry={nodes.soil_soil_mat_0.geometry}
							material={materials.soil_mat}
						/>
					</group>
					<mesh
						geometry={nodes.mug_mug_mat_0.geometry}
						material={materials.mug_mat}
					/>
					{/* DAISY */}
					<group position={[-60.82, 182.04, -7.76]} scale={0.68}>
						<mesh
							geometry={nodes.daisy001_daisy_1_mat_0.geometry}
							material={materials.daisy_1_mat}
						/>
					</group>
					<group
						position={[6.25, 173.86, 0]}
						rotation={[0, 6, 0.2]}
						scale={0.67}
					>
						<mesh
							geometry={nodes.daisy002_daisy_2_mat_0.geometry}
							material={materials.daisy_2_mat}
						/>
					</group>
					<group
						position={[73.1, 185.72, -18.76]}
						rotation={[0, 3.5, 0.3]}
						scale={0.69}
					>
						<mesh
							geometry={nodes.daisy003_daisy_3_mat_0.geometry}
							material={materials.daisy_3_mat}
						/>
					</group>
					<group
						position={[-23.17, 171.49, 44.87]}
						rotation={[-Math.PI, -0.64, -Math.PI]}
						scale={[0.68, 0.68, 0.68]}
					>
						<mesh
							geometry={nodes.daisy004_daisy_4_mat_0.geometry}
							material={materials.daisy_4_mat}
						/>
					</group>
					<group position={[-60.82, 182.04, -7.76]} scale={0.68}>
						<mesh
							geometry={nodes.daisy1_hull_daisy1_hull_mat_0.geometry}
							material={materials.daisy1_hull_mat}
						/>
					</group>
					<group
						position={[-23.17, 171.49, 44.87]}
						rotation={[-Math.PI, -0.64, -Math.PI]}
						scale={[0.68, 0.68, 0.68]}
					>
						<mesh
							geometry={nodes.daisy4_hull_daisy4_hull_mat_0.geometry}
							material={materials.daisy4_hull_mat}
						/>
					</group>
					<group
						position={[73.1, 185.72, -18.76]}
						rotation={[0, 3.5, 0.3]}
						scale={0.69}
					>
						<mesh
							geometry={nodes.daisy3_hull_daisy3_hull_mat_0.geometry}
							material={materials.daisy3_hull_mat}
						/>
					</group>
					<group
						position={[6.25, 173.86, 0]}
						rotation={[0, 6, 0.2]}
						scale={0.67}
					>
						<mesh
							geometry={nodes.daisy2_hull_daisy2_hull_mat_0.geometry}
							material={materials.daisy2_hull_mat}
						/>
					</group>
					{/* FAN */}
					<group
						position={[9.01, 168, 33.97]}
						rotation={[0.2, -0.23, -0.44]}
						scale={[0.77, 0.77, 0.77]}
					>
						<mesh
							geometry={nodes.fan1_fan_1_mat_0.geometry}
							material={materials.fan_1_mat}
						/>
					</group>
					<group
						position={[9.51, 179.52, -41.56]}
						rotation={[-0.26, 40, -0.05]}
						scale={[0.77, 0.77, 0.77]}
					>
						<mesh
							geometry={nodes.fan2_fan_2_mat_0.geometry}
							material={materials.fan_2_mat}
						/>
					</group>
					<group
						position={[-67.13, 123.3, 40.65]}
						rotation={[-0.01, -0.77, -0.06]}
						scale={[0.77, 0.77, 0.77]}
					>
						<mesh
							geometry={nodes.fan3_fan_3_mat_0.geometry}
							material={materials.fan_3_mat}
						/>
					</group>

					<group
						position={[9.01, 168, 33.97]}
						rotation={[0.2, -0.23, -0.44]}
						scale={[0.77, 0.77, 0.77]}
					>
						<mesh
							geometry={nodes.fan1_hull_fan_1_hull_mat_0.geometry}
							material={materials.fan_1_hull_mat}
						/>
					</group>
					<group
						position={[9.51, 179.52, -41.56]}
						rotation={[-0.26, 40, -0.05]}
						scale={[0.77, 0.77, 0.77]}
					>
						<mesh
							geometry={nodes.fan2_hull_fan2_hull_mat_0.geometry}
							material={materials.fan2_hull_mat}
						/>
					</group>
					<group
						position={[-67.13, 123.3, 40.65]}
						rotation={[-0.01, -0.77, -0.06]}
						scale={[0.77, 0.77, 0.77]}
					>
						<mesh
							geometry={nodes.fan3_hull_fan3_hull_mat_0.geometry}
							material={materials.fan3_hull_mat}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/models/fan.glb');
