/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Brew (https://sketchfab.com/Espressoul)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/day-4-knot-inktober-2021-1d08825ab45f4e11ab3c952fde7cef3a
title: Day 4 Knot - INKTOBER 2021
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Knot({ ...props }) {
	const group = useRef();
	const { nodes, materials } = useGLTF('/models/knot.glb');
	return (
		<group ref={group} {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<mesh
						geometry={nodes.hand_hand_mat_0.geometry}
						material={materials.hand_mat}
					/>
					<mesh
						geometry={nodes.begleri_2_begleri2_mat_0.geometry}
						material={materials.begleri2_mat}
					/>
					<mesh
						geometry={nodes.begleri_cord_begleri_cord_mat_0.geometry}
						material={materials.begleri_cord_mat}
					/>
					<mesh
						geometry={nodes.begleri_2_hull_begleri2hull_mat_0.geometry}
						material={materials.begleri2hull_mat}
					/>
					<mesh
						geometry={
							nodes.begleri_cord_hull001_begleri_cord_hull_mat_0.geometry
						}
						material={materials.begleri_cord_hull_mat}
					/>
					<mesh
						geometry={nodes.begleri1_begleri1_mat_0.geometry}
						material={materials.begleri1_mat}
					/>
					<mesh
						geometry={nodes.speed__0.geometry}
						material={nodes.speed__0.material}
					/>
					<mesh
						geometry={nodes.speed1__0.geometry}
						material={nodes.speed1__0.material}
					/>
					<mesh
						geometry={nodes.hand_hull_hand_hull_mat_0.geometry}
						material={materials.hand_hull_mat}
					/>
					<mesh
						geometry={nodes.begleri_1_hull_begleri1Hull_mat_0.geometry}
						material={materials.begleri1Hull_mat}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/models/knot.glb');
